### ISSUE TITLE
繁體系統上使用有問題

### ISSUE THREAD

**Issue by blackboyhc** [jiajunsu/calculator_of_Onmyoji#27]

**Comment by blackboyhc** [comment]
同樣一個導出文件在簡體系統上使用這個工具可以計算出結果，但是在繁體系統上得不到結果，總是顯示0個結果
![image](https://user-images.githubusercontent.com/683130/50476020-7246d300-0a01-11e9-8c4f-f0713b1a7418.png)

**Comment by jiajunsu** [comment]
拿4.0版本再试一下看看

**Comment by blackboyhc** [comment]
> 拿4.0版本再试一下看看

4.0版还是不行，一样的结果。

**Comment by jiajunsu** [comment]
> > 拿4.0版本再试一下看看
> 
> 4.0版还是不行，一样的结果。

能把Input args那一行，双击打开之后的详情贴一下吗

**Comment by blackboyhc** [comment]
> > > 拿4.0版本再试一下看看
> > 
> > 
> > 4.0版还是不行，一样的结果。
> 
> 能把Input args那一行，双击打开之后的详情贴一下吗

![image](https://user-images.githubusercontent.com/683130/50619369-d1da3c80-0f33-11e9-9a03-7760b467dacf.png)
好像是有乱码

**Comment by jiajunsu** [comment]
这个估计是UI的问题了，解码没抛异常，说明decode是通过的。

我把里面的这段编码用big5是可以解的，不过中间缺了一个字  
\xa7\xf0?\xa5[\xa6\xa8，问号的地方少了个字

**Comment by blackboyhc** [comment]
这是我用命令行执行的截图，好像是同样的问题，这样可以排除UI的问题吧？
![image](https://user-images.githubusercontent.com/683130/50668756-1d581d80-0ffc-11e9-9772-e72c9e521413.png)
`PS D:\personal\yys\calculator\dist> .\cal_mitama.exe yuhun_1544545125.xls yuhun_1544545125-result.xls -M 针女,4 -P 暴击,
90.暴击伤害,50 -2P 攻击加成,55 -4P 攻击加成,55 -6P 暴击,55 -IG 天狗
Input args: Namespace(all_suit=True, attack_only=False, damage_limit='0,0,0', effective_secondary_prop='', effective_secondary_prop_num='', fth_prop_value='\xa7\xf0?\xa5[\xa6\xa8,55', health_limit='0,0,0', ignore_serial='\xa4\xd1\xaa\xaf', mitama_suit='?\xa4k,4', output_file='yuhun_1544545125-result.xls', prop_limit='\xbc\xc9?,90.\xbc\xc9??\xae`,50', sec_prop_value='\xa7\xf0?\xa5[\xa6\xa8,55', source_data='yuhun_1544545125.xls', sth_prop_value='\xbc\xc9?,55', upper_prop_limit='')
Loading data finish
Start calculating
mitama nums by loc is [21, 23, 21, 25, 31, 25]
after filter by loc prop and type [21, 0, 21, 0, 31, 0]
Total combinations: 0
We got 0 results
PS D:\personal\yys\calculator\dist>`

**Comment by jiajunsu** [comment]
命令行下输入一下chcp，看看默认编码是什么

看起来是所有的'击'的解析都出错了

**Comment by blackboyhc** [comment]
> 命令行下输入一下chcp，看看默认编码是什么
> 
> 看起来是所有的'击'的解析都出错了
`PS D:\personal\yys\calculator\dist> chcp
使用中的字碼頁: 950`

**Comment by blackboyhc** [comment]
> 命令行下输入一下chcp，看看默认编码是什么
> 
> 看起来是所有的'击'的解析都出错了

`PS D:\personal\yys\calculator\dist> chcp
使用中的字碼頁: 950`

**Comment by jiajunsu** [comment]
windows命令行的编码处理太捉急了，我重新做个web版的 UI吧

**Comment by blackboyhc** [comment]
在繁体系统上还发现一个问题，应该还是和编码相关的，不另开了 @jiajunsu 
我使用result_combination的时候会出现下面的错误信息：
`Files below will be calculated:
['D:\\personal\\yys\\calculator\\dist\\yuhun_1549847459-result.xls']

Traceback (most recent call last):
  File "calculator_of_Onmyoji\result_combination.py", line 282, in <module>
  File "calculator_of_Onmyoji\result_combination.py", line 262, in main
  File "calculator_of_Onmyoji\result_combination.py", line 224, in input_expect_combs_counts
  File "calculator_of_Onmyoji\result_combination.py", line 249, in get_encode_str
UnicodeEncodeError: 'cp950' codec can't encode character u'\u8bf7' in position 0: illegal multibyte sequence


Press any key to exit`

**Comment by somethingmou** [comment]
编码类问题是不是升级成python3后就会好很多？如果是的话，干脆 @jiajunsu  大佬就早点升级成python3吧，可以用python3自带的2to3工具一键升级，还是很方便的。
