### ISSUE TITLE
启用webui

### ISSUE THREAD

**Issue by jiajunsu** [jiajunsu/calculator_of_Onmyoji#28]
基于html5开发新UI界面

后台cm_server.py，在本机127.0.0.1开放端口，默认端口2019，通过配置文件可修改。

```.\server.conf
[global]  
host = 127.0.0.1
port = 2019
```

**Comment by chujie** [comment]
可以考虑jinja2+bootstrap做模板？

**Comment by jiajunsu** [comment]
> 可以考虑jinja2+bootstrap做模板？

感谢，我学一下bootstrap

**Comment by yinxin630** [comment]
你好, 我是一个前端开发, 有什么可以帮助的吗

**Comment by jiajunsu** [comment]
> 你好, 我是一个前端开发, 有什么可以帮助的吗

现在基于bootstrap开了一个比较挫的头，剩余的UI内容还没补充上去。欢迎帮忙完成这个UI

> 能不能脱离服务端, 把计算逻辑也放在前端呢? Python没学过, 计算逻辑没看懂

计算量比较大，直接在前端完成浏览器受不了

**Comment by yinxin630** [comment]
bootstrap我基本没用过. UI有源码地址吗

**Comment by jiajunsu** [comment]
> 计算量大的问题, 现在chrome浏览器V8引擎速度已经很快了, 多线程也有WebWorker支持, 追求极致还可以把核心计算用WebAssembly实现, 当然兼容性覆盖不到所有常用浏览器
> 好处有很多:
> 
> * 跨平台(MAC党欢呼)
> * 不用下载, 部署一份, 大家打开浏览器就能用
> * 可以加账号机制, 把一些常用配置跨机器存下来(多机党)

对前端不熟悉……现在python计算是结果直接输出到excel，如果结果数据量比较大，计算时会消耗几G的内存，不知道浏览器能不能吃得下。

如果都能满足的话，的确可以用前端重写一下

**Comment by yinxin630** [comment]
> > bootstrap我基本没用过. UI有源码地址吗
> 
> https://github.com/jiajunsu/calculator_of_Onmyoji/tree/master/calculator_of_Onmyoji/templates

现在有UI设计稿之类的吗, 我倾向于单开一个项目, 技术栈上用现在常用的, JQ不想糊了..

**Comment by jiajunsu** [comment]
> > > bootstrap我基本没用过. UI有源码地址吗
> > 
> > 
> > https://github.com/jiajunsu/calculator_of_Onmyoji/tree/master/calculator_of_Onmyoji/templates
> 
> 现在有UI设计稿之类的吗, 我倾向于单开一个项目, 技术栈上用现在常用的, JQ不想糊了..

release里面下最新的压缩包，dist目录下的CMUI.exe可以做参考

**Comment by chujie** [comment]
全部web端计算的话，感觉内存问题很难解决，之前我自己写的web版工具加载几千条的结果文件都会卡死。
我用vuejs写了一个prototype，基本功能实现了，就是很丑...

**Comment by yinxin630** [comment]
> 全部web端计算的话，感觉内存问题很难解决，之前我自己写的web版工具加载几千条的结果文件都会卡死。
> 我用vuejs写了一个prototype，基本功能实现了，就是很丑...

这个可以从长计议

**Comment by yinxin630** [comment]
> > > > bootstrap我基本没用过. UI有源码地址吗
> > > 
> > > 
> > > https://github.com/jiajunsu/calculator_of_Onmyoji/tree/master/calculator_of_Onmyoji/templates
> > 
> > 
> > 现在有UI设计稿之类的吗, 我倾向于单开一个项目, 技术栈上用现在常用的, JQ不想糊了..
> 
> release里面下最新的压缩包，dist目录下的CMUI.exe可以做参考

好的, 有空我试试.
工作比较忙, 又要肝YYS...

**Comment by yinxin630** [comment]
![image](https://user-images.githubusercontent.com/6939365/51485967-6836ab00-1dda-11e9-9245-5a45cb2fd48a.png)
完成了基础的UI界面

**Comment by chujie** [comment]
> ![image](https://user-images.githubusercontent.com/6939365/51485967-6836ab00-1dda-11e9-9245-5a45cb2fd48a.png)
> 完成了基础的UI界面. 源码: https://github.com/yinxin630/yys-yuhun-calculator-ui

鸩好看！
一个小的建议就是套装属性那边，可以改成跟目标属性一样，逐条添加想要的御魂种类或者御魂套装属性以及套装个数吗，现在支持散件的计算，就可以计算3个生命两件套或者3个暴击两件套之类的。

**Comment by jiajunsu** [comment]
> 完成了基础的UI界面. 源码: https://github.com/yinxin630/yys-yuhun-calculator-ui

666

问个小白问题，用vue做的UI，放在使用者本地运行的话，会不会依赖比较多

如果依赖比较多的话，我就考虑搭个web服务器，使用者直接在线访问ui，ui调用本地的127.0.0.1接口进行计算

**Comment by yinxin630** [comment]
@chujie 后面可以优化, 因为我对作者的命令行版还不熟悉, 现在就是照搬的桌面版功能

**Comment by yinxin630** [comment]
@jiajunsu 不会的, 一样可以打包出来, 放本地双击打开. 不过以file协议打开浏览器可能有较多限制(大概不能发ajax请求, 回头我试试)
最好还是提供一个简单的静态文件web server, 比如node上[http-server](https://www.npmjs.com/package/http-server)这种, 集成到你的计算server上

**Comment by jiajunsu** [comment]
> @jiajunsu 不会的, 一样可以打包出来, 放本地双击打开. 不过以file协议打开浏览器可能有较多限制(大概不能发ajax请求, 回头我试试)
> 最好还是提供一个简单的静态文件web server, 比如node上[http-server](https://www.npmjs.com/package/http-server)这种, 集成到你的计算server上

如果能直接以web-server本地启动，并且对本地运行环境没有额外的依赖，那我就可以打包一起发布了，还能省下服务器的钱:)。现在主线上已经做了web服务器的部分，cm_server.py本地运行，会通过flask加载template/index.html作为主页。

回头我再调整一下POST接口的参数，让参数格式和命令行参数保持一致，通过body，以{key:value}的方式传入

**Comment by chujie** [comment]
> @chujie 后面可以优化, 因为我对作者的命令行版还不熟悉, 现在就是照搬的桌面版功能

现在桌面版也没有最新的御魂有效副属性过滤，-ESP和-ESPN的支持。

**Comment by yinxin630** [comment]
> > @chujie 后面可以优化, 因为我对作者的命令行版还不熟悉, 现在就是照搬的桌面版功能
> 
> 现在桌面版也没有最新的御魂有效副属性过滤，-ESP和-ESPN的支持。

好的, 回头我熟悉下命令行版的全功能

**Comment by jiajunsu** [comment]
> > @chujie 后面可以优化, 因为我对作者的命令行版还不熟悉, 现在就是照搬的桌面版功能
> 
> 现在桌面版也没有最新的御魂有效副属性过滤，-ESP和-ESPN的支持。

等前后台对接调通之后，这部分内容可以继续加

**Comment by chujie** [comment]
> > @jiajunsu 不会的, 一样可以打包出来, 放本地双击打开. 不过以file协议打开浏览器可能有较多限制(大概不能发ajax请求, 回头我试试)
> > 最好还是提供一个简单的静态文件web server, 比如node上[http-server](https://www.npmjs.com/package/http-server)这种, 集成到你的计算server上
> 
> 如果能直接以web-server本地启动，并且对本地运行环境没有额外的依赖，那我就可以打包一起发布了，还能省下服务器的钱:)。现在主线上已经做了web服务器的部分，cm_server.py本地运行，会通过flask加载template/index.html作为主页。
> 
> 回头我再调整一下POST接口的参数，让参数格式和命令行参数保持一致，通过body，以{key:value}的方式传入

之前测试的时候写过post接口的支持: [cm_server.py](https://github.com/chujie/calculator_of_Onmyoji/blob/dev/web-ui/calculator_of_Onmyoji/cm_server.py)，后端非常简单，但是需要前端适配所有的参数对应的key。
而且后端已经有flask作为static server，可以直接渲染ui-project生成的页面。

**Comment by somethingmou** [comment]
建议预设方案的编写规则与命令行的一致，这样方便使用现成的命令行，不需要再次学习新的编码规则。

**Comment by jiajunsu** [comment]
> @jiajunsu 感觉现在这样实现也没什么问题，只要定义好api的接口就可以，适配的函数在前端也很容易实现的。

同样的字符串处理逻辑，还是尽量避免前后端各实现一套，以后如果要调整会比较麻烦。我晚上看看能不能有时间改下吧

**Comment by yinxin630** [comment]
我好像装不上依赖啊, 执行 `pip install -r requirements.txt` 和 `pip install .` 都报错
```
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/wheel.py", line 316, in clobber
    ensure_dir(destdir)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/Library/Python/2.7/site-packages/xlrd-1.2.0.dist-info'
```

**Comment by yinxin630** [comment]
😂 python实在看不懂, 我需要一个接口文档

**Comment by yinxin630** [comment]
还有一个问题, web不能获取到用户选择的文件路径, 只能读取文件内容再传给后端

**Comment by yinxin630** [comment]
https://cdn.suisuijiang.com/calculator-web-ui.zip
这是一个打包后的可以预览的版本

**Comment by jiajunsu** [comment]
> 😂 python实在看不懂, 我需要一个接口文档

```POST http://0.0.0.0:2019/calculate
body:
{key: value}
```

key和value的格式参考https://github.com/jiajunsu/calculator_of_Onmyoji#usage-of-calculator

例如--mitama-suit，对应的key为mitama_suit，value为 御魂1,数量1.御魂2,数量2

**Comment by jiajunsu** [comment]
> 还有一个问题, web不能获取到用户选择的文件路径, 只能读取文件内容再传给后端

文件的事情，我也发现了。不过都是本机运行的，再搞上传下载没必要。

考虑规避一下，参数传递的时候，用当前路径+文件名的方式拼装一下好了

**Comment by jiajunsu** [comment]
> https://cdn.suisuijiang.com/calculator-web-ui.zip
> 这是一个打包后的, 可以预览的版本, 没有与后端交互
> 解压, 双击打开 `index.html` 即可

标题的名字改一下吧，就叫 阴阳师御魂计算器，去掉 组合 两字，和现在的NGA帖子保持一致比较好。

六号位属性这里捉个错别字，```s/爆伤/暴伤/g```

另外御魂套装选择这里，我原来是打算做成这种样子的，不区分 主和辅助的，直接选择 套装类型和数量，这样可以做2+2+2的处理。并且支持的类型中包括套装加成的类型，不仅仅是套装名称

![image](https://user-images.githubusercontent.com/16359131/51550527-7272ab00-1ea7-11e9-8f16-a619c9f6608d.png)

**Comment by jiajunsu** [comment]
> https://cdn.suisuijiang.com/calculator-web-ui.zip
> 这是一个打包后的, 可以预览的版本, 没有与后端交互
> 解压, 双击打开 `index.html` 即可

再次赞美UI的风格，大佬出手立马高大上了，比我自己搞的nb多了~~

**Comment by chujie** [comment]
> > 还有一个问题, web不能获取到用户选择的文件路径, 只能读取文件内容再传给后端
> 
> 文件的事情，我也发现了。不过都是本机运行的，再搞上传下载没必要。
> 
> 考虑规避一下，参数传递的时候，用当前路径+文件名的方式拼装一下好了

关于文件，我反而觉得上传文件内容比路径更可靠一些，可以不用考虑不同系统文件路径的差异以及读取权限的问题，而且上传下载都在本地完成速度也不是问题。

**Comment by yinxin630** [comment]
御魂筛选条件等我调通后端后看看怎么样更方便吧.
你能发个示例的成功http请求吗, 用postman或者curl请求都行

**Comment by jiajunsu** [comment]
> 御魂筛选条件等我调通后端后看看怎么样更方便吧.
> 你能发个示例的成功http请求吗, 用postman或者curl请求都行

后台的参数解析还有点问题，我再改改

**Comment by jiajunsu** [comment]
> 御魂筛选条件等我调通后端后看看怎么样更方便吧.
> 你能发个示例的成功http请求吗, 用postman或者curl请求都行

后端调整了下，这个我测试是ok的。现在所有的参数都需要填充默认值

curl http://127.0.0.1:2019/calculate -X POST -H "Content-Type: application/json" -d '{"source_data":"/path/to/example/data_Template.xls","mitama_suit":"针女,4", "output_file":"/path/to/data_Template-result.xls", "prop_limit":"暴击,90", "upper_prop_limit":",0", "sec_prop_value":",0", "fth_prop_value":",0", "sth_prop_value":",0", "ignore_serial":"","all_suit":"True","damage_limit":"0,0,0", "health_limit":"0,0,0","attack_only":"False","effective_secondary_prop":"","effective_secondary_prop_num":""}'

**Comment by yinxin630** [comment]
```
$ curl http://127.0.0.1:2019/calculate -X POST -H "Content-Type: application/json" -d '{"source_data":"/Users/yinxin/github/calculator_of_Onmyoji/example/data_Template.xls","mitama_suit":"针女,4", "output_file":"/Users/yinxin/github/calculator_of_Onmyoji/data_Template-result.xls", "prop_limit":"暴击,90", "upper_prop_limit":",0", "sec_prop_value":",0", "fth_prop_value":",0", "sth_prop_value":",0", "ignore_serial":"","all_suit":"True","damage_limit":"0,0,0", "health_limit":"0,0,0","attack_only”:”True”,”effective_secondary_prop":"","effective_secondary_prop_num":""}'
Traceback (most recent call last):
  File "./calculator_of_Onmyoji/cm_server.py", line 27, in calculate
    calculator = cal_mitama.Calculator(params)
  File "/Library/Python/2.7/site-packages/calculator_of_Onmyoji/cal_mitama.py", line 78, in __init__
    self.init_from_params(params)
  File "/Library/Python/2.7/site-packages/calculator_of_Onmyoji/cal_mitama.py", line 221, in init_from_params
    setattr(self, key, value)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u201d' in position 11: ordinal not in range(128)
```

**Comment by jiajunsu** [comment]
> ```
> $ curl http://127.0.0.1:2019/calculate -X POST -H "Content-Type: application/json" -d '{"source_data":"/Users/yinxin/github/calculator_of_Onmyoji/example/data_Template.xls","mitama_suit":"针女,4", "output_file":"/Users/yinxin/github/calculator_of_Onmyoji/data_Template-result.xls", "prop_limit":"暴击,90", "upper_prop_limit":",0", "sec_prop_value":",0", "fth_prop_value":",0", "sth_prop_value":",0", "ignore_serial":"","all_suit":"True","damage_limit":"0,0,0", "health_limit":"0,0,0","attack_only”:”True”,”effective_secondary_prop":"","effective_secondary_prop_num":""}'
> Traceback (most recent call last):
>   File "./calculator_of_Onmyoji/cm_server.py", line 27, in calculate
>     calculator = cal_mitama.Calculator(params)
>   File "/Library/Python/2.7/site-packages/calculator_of_Onmyoji/cal_mitama.py", line 78, in __init__
>     self.init_from_params(params)
>   File "/Library/Python/2.7/site-packages/calculator_of_Onmyoji/cal_mitama.py", line 221, in init_from_params
>     setattr(self, key, value)
> UnicodeEncodeError: 'ascii' codec can't encode character u'\u201d' in position 11: ordinal not in range(128)
> ```

你本地代码没更新吧……
```
git pull  
pip install . -U
python calculator_of_Onmyoji/cm_server.py
```

**Comment by yinxin630** [comment]
@jiajunsu 我pull了, 但是没install... 😕Python还是玩不明白

**Comment by jiajunsu** [comment]
> @jiajunsu 我pull了, 但是没install... Python还是玩不明白

没事没事，我对前端也不熟。还要学一下打包UI

我想想看要不要把ui的git作为submodule加进来

**Comment by yinxin630** [comment]
> > @jiajunsu 我pull了, 但是没install... Python还是玩不明白
> 
> 没事没事，我对前端也不熟。还要学一下打包UI
> 
> 我想想看要不要把ui的git作为submodule加进来

没啥必要, 前端源码也没法直接运行, 就要个打包后的就好

**Comment by jiajunsu** [comment]
@yinxin630
attack_only 这个参数没传

**Comment by yinxin630** [comment]
@jiajunsu  有几个问题:
* `source_data` 和 `output_file` 两个参数, source_data我只能拿到文件名, output_file无能为力
* 是否能提供打开结果excel文件的接口
* 接口应该响应json数据, 成功时返回结果条数, 展示给用户, 失败时返回用户可理解的文案

**Comment by jiajunsu** [comment]
> @jiajunsu 有几个问题:
> 
> * `source_data` 和 `output_file` 两个参数, source_data我只能拿到文件名, output_file无能为力
> * 是否能提供打开结果excel文件的接口
> * 接口应该响应json数据, 成功时返回结果条数, 展示给用户, 失败时返回用户可理解的文案

嗯，文件名就行了。这几点我周日晚上争取处理一下吧。年底事情好多:(

失败的错误码，估计要再晚点搞

**Comment by jiajunsu** [comment]
> * `source_data` 和 `output_file` 两个参数, source_data我只能拿到文件名, output_file无能为力


新增了src_filename，前台直接传文件名就行，限定文件必须在后台的运行目录下。
https://github.com/jiajunsu/calculator_of_Onmyoji#usage-of-cm-server
